In [78]:
import pandas as pd
import numpy as np
weather = pd.read_csv('2008_weather_cleaned.csv')
atl = pd.read_csv('atl_data.csv')

In [79]:
weather.head()

,Month,DayofMonth,Temp,Temp_Avg,Visibility_High,Visibility_Avg,Wind_High,Wind_Avg,Precip_Sum
0,1,1,47,39,10,10,30,16,T
1,1,2,30,25,10,10,28,18,T
2,1,3,40,28,10,10,16,5,0
3,1,4,47,36,10,10,10,3,0
4,1,5,55,43,10,10,14,6,0

In [80]:
atl.columns

Index([u'Month', u'DayofMonth', u'DayOfWeek', u'DepTime', u'CRSDepTime',
       u'UniqueCarrier', u'FlightNum', u'Distance', u'Dest', u'Cancelled'],
      dtype='object')

In [81]:
# atl = atl.drop('Unnamed: 0', 1)

In [82]:
atl.head()

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,UniqueCarrier,FlightNum,Distance,Dest,Cancelled
0,1,19,6,916.0,900,XE,1265,745,ATL,0
1,1,16,3,2102.0,1739,XE,2622,689,ATL,0
2,1,22,2,919.0,900,XE,2023,554,ATL,0
3,1,1,2,1127.0,1035,XE,1221,745,ATL,0
4,1,5,6,1733.0,1720,XE,2562,689,ATL,0

In [83]:
type(weather)

pandas.core.frame.DataFrame

In [84]:
merged = atl.merge(weather, how='left')

In [85]:
merged.columns

Index([u'Month', u'DayofMonth', u'DayOfWeek', u'DepTime', u'CRSDepTime',
       u'UniqueCarrier', u'FlightNum', u'Distance', u'Dest', u'Cancelled',
       u'Temp ', u'Temp_Avg', u'Visibility_High', u'Visibility_Avg',
       u'Wind_High', u'Wind_Avg', u'Precip_Sum'],
      dtype='object')

In [86]:
merged = merged.drop('Precip_Sum',1)

In [87]:
merged
# merged.to_csv('atl_weather.csv',index= False)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,UniqueCarrier,FlightNum,Distance,Dest,Cancelled,Temp,Temp_Avg,Visibility_High,Visibility_Avg,Wind_High,Wind_Avg
0,1,19,6,916.0,900,XE,1265,745,ATL,0,43,36,10,7,22,10
1,1,16,3,2102.0,1739,XE,2622,689,ATL,0,39,35,10,6,23,11
2,1,22,2,919.0,900,XE,2023,554,ATL,0,41,37,10,7,17,7
3,1,1,2,1127.0,1035,XE,1221,745,ATL,0,47,39,10,10,30,16
4,1,5,6,1733.0,1720,XE,2562,689,ATL,0,55,43,10,10,14,6
5,1,2,3,1305.0,1245,XE,2184,689,ATL,0,30,25,10,10,28,18
6,1,5,6,754.0,742,XE,2506,689,ATL,0,55,43,10,10,14,6
7,1,1,2,2133.0,2045,XE,2213,689,ATL,0,47,39,10,10,30,16
8,1,15,2,1752.0,1739,XE,2622,689,ATL,0,49,40,10,10,21,10
9,1,12,6,737.0,730,XE,2792,689,ATL,0,59,48,10,10,10,5
10,1,6,7,1030.0,1020,XE,2342,689,ATL,0,67,54,10,10,13,5
11,1,2,3,2115.0,2045,XE,2213,689,ATL,0,30,25,10,10,28,18
12,1,2,3,1717.0,1655,XE,2464,554,ATL,0,30,25,10,10,28,18
13,1,22,2,1511.0,1455,XE,2362,689,ATL,0,41,37,10,7,17,7
14,1,19,6,1828.0,1740,XE,2464,554,ATL,0,43,36,10,7,22,10
15,1,9,3,1759.0,1739,XE,2622,689,ATL,0,64,61,10,9,17,5
16,1,29,2,1801.0,1739,XE,2622,689,ATL,0,65,52,10,10,28,12
17,1,6,7,2131.0,2045,XE,2213,689,ATL,0,67,54,10,10,13,5
18,1,4,5,1800.0,1655,XE,2464,554,ATL,0,47,36,10,10,10,3
19,1,3,4,1041.0,730,XE,2206,689,ATL,0,40,28,10,10,16,5
20,1,3,4,2054.0,2045,XE,2213,689,ATL,0,40,28,10,10,16,5
21,1,23,3,1800.0,1739,XE,2622,689,ATL,0,50,45,10,6,13,7
22,1,3,4,1223.0,1115,XE,2432,554,ATL,0,40,28,10,10,16,5
23,1,5,6,2020.0,2010,XE,1286,745,ATL,0,55,43,10,10,14,6
24,1,18,5,1751.0,1739,XE,2622,689,ATL,0,54,46,10,8,12,7
25,1,1,2,1940.0,1855,YV,7146,1199,ATL,0,47,39,10,10,30,16
26,1,1,2,843.0,837,YV,7201,533,ATL,0,47,39,10,10,30,16
27,1,2,3,1457.0,1420,YV,2645,227,ATL,0,30,25,10,10,28,18
28,1,2,3,2007.0,1855,YV,7146,1199,ATL,0,30,25,10,10,28,18
29,1,2,3,1703.0,1634,YV,7269,533,ATL,0,30,25,10,10,28,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106868,12,13,6,1123.0,1113,DL,988,595,ATL,0,48,38,10,10,13,7
106869,12,13,6,1012.0,1005,DL,1029,581,ATL,0,48,38,10,10,13,7
106870,12,13,6,1455.0,1400,DL,1032,1587,ATL,0,48,38,10,10,13,7
106871,12,13,6,1230.0,1151,DL,1054,2182,ATL,0,48,38,10,10,13,7
106872,12,13,6,2346.0,2320,DL,1060,2182,ATL,0,48,38,10,10,13,7
106873,12,13,6,955.0,948,DL,1080,1747,ATL,0,48,38,10,10,13,7
106874,12,13,6,1244.0,1235,DL,1082,859,ATL,0,48,38,10,10,13,7
106875,12,13,6,1354.0,1330,DL,1088,1747,ATL,0,48,38,10,10,13,7
106876,12,13,6,1205.0,1135,DL,1097,215,ATL,0,48,38,10,10,13,7
106877,12,13,6,1703.0,1555,DL,1198,445,ATL,0,48,38,10,10,13,7
106878,12,13,6,847.0,840,DL,1215,373,ATL,0,48,38,10,10,13,7
106879,12,13,6,1150.0,1128,DL,1279,859,ATL,0,48,38,10,10,13,7
106880,12,13,6,1355.0,1345,DL,1285,760,ATL,0,48,38,10,10,13,7
106881,12,13,6,1805.0,1718,DL,1293,516,ATL,0,48,38,10,10,13,7
106882,12,13,6,1618.0,1604,DL,1400,874,ATL,0,48,38,10,10,13,7
106883,12,13,6,1443.0,1336,DL,1470,874,ATL,0,48,38,10,10,13,7
106884,12,13,6,1422.0,1355,DL,1476,1589,ATL,0,48,38,10,10,13,7
106885,12,13,6,1159.0,1126,DL,1512,1589,ATL,0,48,38,10,10,13,7
106886,12,13,6,1100.0,1045,DL,1530,692,ATL,0,48,38,10,10,13,7
106887,12,13,6,1200.0,1150,DL,1538,2172,ATL,0,48,38,10,10,13,7
106888,12,13,6,1149.0,1048,DL,1547,545,ATL,0,48,38,10,10,13,7
106889,12,13,6,1251.0,1210,DL,1553,516,ATL,0,48,38,10,10,13,7
106890,12,13,6,1429.0,1355,DL,1563,906,ATL,0,48,38,10,10,13,7
106891,12,13,6,1254.0,1221,DL,1609,432,ATL,0,48,38,10,10,13,7
106892,12,13,6,1531.0,1522,DL,1612,692,ATL,0,48,38,10,10,13,7
106893,12,13,6,1552.0,1520,DL,1620,151,ATL,0,48,38,10,10,13,7
106894,12,13,6,1250.0,1220,DL,1621,906,ATL,0,48,38,10,10,13,7
106895,12,13,6,657.0,600,DL,1631,481,ATL,0,48,38,10,10,13,7
106896,12,13,6,1251.0,1240,DL,1639,533,ATL,0,48,38,10,10,13,7
106897,12,13,6,1110.0,1103,DL,1641,874,ATL,0,48,38,10,10,13,7

In [88]:
# merged.isnull().any().any()

In [93]:
# bins = [-1,0,1]
# binned = pd.cut(merged['Cancelled'],bins,labels=['not_cancelled','cancelled'])
# merged['CancelledFlights'] = binned
# dummies = pd.get_dummies(merged['CancelledFlights'])

In [94]:
# merged = merged.combine_first(dummies)

In [95]:
merged.head()
# merged['not_cancelled'].dtype

,CRSDepTime,Cancelled,CancelledFlights,DayOfWeek,DayofMonth,DepTime,Dest,Distance,FlightNum,Month,Temp,Temp_Avg,UniqueCarrier,Visibility_Avg,Visibility_High,Wind_Avg,Wind_High,cancelled,not_cancelled
0,900,0,not_cancelled,6,19,916.0,ATL,745,1265,1,43,36,XE,7,10,10,22,0.0,1.0
1,1739,0,not_cancelled,3,16,2102.0,ATL,689,2622,1,39,35,XE,6,10,11,23,0.0,1.0
2,900,0,not_cancelled,2,22,919.0,ATL,554,2023,1,41,37,XE,7,10,7,17,0.0,1.0
3,1035,0,not_cancelled,2,1,1127.0,ATL,745,1221,1,47,39,XE,10,10,16,30,0.0,1.0
4,1720,0,not_cancelled,6,5,1733.0,ATL,689,2562,1,55,43,XE,10,10,6,14,0.0,1.0

In [96]:
merged.head()

,CRSDepTime,Cancelled,CancelledFlights,DayOfWeek,DayofMonth,DepTime,Dest,Distance,FlightNum,Month,Temp,Temp_Avg,UniqueCarrier,Visibility_Avg,Visibility_High,Wind_Avg,Wind_High,cancelled,not_cancelled
0,900,0,not_cancelled,6,19,916.0,ATL,745,1265,1,43,36,XE,7,10,10,22,0.0,1.0
1,1739,0,not_cancelled,3,16,2102.0,ATL,689,2622,1,39,35,XE,6,10,11,23,0.0,1.0
2,900,0,not_cancelled,2,22,919.0,ATL,554,2023,1,41,37,XE,7,10,7,17,0.0,1.0
3,1035,0,not_cancelled,2,1,1127.0,ATL,745,1221,1,47,39,XE,10,10,16,30,0.0,1.0
4,1720,0,not_cancelled,6,5,1733.0,ATL,689,2562,1,55,43,XE,10,10,6,14,0.0,1.0

In [97]:
# merged.to_csv('atl_weather_binned.csv')

In [99]:
merged['not_cancelled'].value_counts()

1.0    106872
0.0        26
Name: not_cancelled, dtype: int64

In [100]:
merged['cancelled'].value_counts()

0.0    106872
1.0        26
Name: cancelled, dtype: int64